### ISSUE TITLE
I can't slice complex object - Operator bpy.ops.object.mode_set.poll() Context missing active object

### ISSUE THREAD

**Issue by Stanislav1912** [rgsouthall/laser_slicer#6]
Hello! I can't slice complex object, only a single cube. All modificators are applied. File is saved. Trying to slice in an object mode. Blender 4.0
Here's an error message:
`Python: Traceback (most recent call last):
  File "K:\Program Files (x86)\blender-4.0.0-windows-x64\4.0\scripts\addons\laser_slicer-master\__init__.py", line 319, in execute
    slicer(context.scene.slicer_settings)
  File "K:\Program Files (x86)\blender-4.0.0-windows-x64\4.0\scripts\addons\laser_slicer-master\__init__.py", line 83, in slicer
    bpy.ops.object.mode_set(mode = 'EDIT')
  File "K:\Program Files (x86)\blender-4.0.0-windows-x64\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object
`
![image](https://github.com/rgsouthall/laser_slicer/assets/151841484/0b2e98c3-3f32-44fe-965c-c38b22b109bc)
![image](https://github.com/rgsouthall/laser_slicer/assets/151841484/298b5b2e-d319-46a1-8406-bb76e8918f47)
![image](https://github.com/rgsouthall/laser_slicer/assets/151841484/426f8b4a-6783-4864-afb2-e181b9007a11)

**Comment by rgsouthall** [comment]
Do you have an object selected?

**Comment by Stanislav1912** [comment]
> Do you have an object selected?

Sure! That was first thing that I thought about (missing active object)

**Comment by Stanislav1912** [comment]
> Do you have an object selected?

I figured it to work by appending the desired object to a new blend file, it worked, but I can't guess why.
